# Generated by Django 6.0.6 on 2026-06-10 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=25, null=True)),
                ('view', models.CharField(max_length=100, verbose_name='URL Name')),
                ('nav', models.BooleanField(default=False, verbose_name='Include in Navigation?')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('blurb', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table_comment': 'Stores data for Page content and Navbar Links',
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('root', models.BooleanField(default=False, verbose_name='Is Navigation Root?')),
                ('has_children', models.BooleanField(default=False, verbose_name='Has child pages?')),
                ('root_pos', models.IntegerField(blank=True, null=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.page')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table_comment': 'Profiles for learner tracking linked to django.contrib.auth.user',
            },
        ),
    ]
