# Generated by Django 6.0.6 on 2026-06-14 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='page',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='profile',
            table_comment=None,
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
