# Generated by Django 6.0.6 on 2026-09-07 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "on_time",
                    models.BooleanField(
                        choices=[
                            ("1", "No show"),
                            ("2", "Arrives >15m late"),
                            ("3", "Arrives on time"),
                        ],
                        verbose_name="Arrived on time",
                    ),
                ),
                (
                    "dress",
                    models.BooleanField(
                        choices=[
                            ("1", "Dressed inappropriately"),
                            ("2", "Dressed appropriately"),
                        ],
                        verbose_name="Appropriately dressed",
                    ),
                ),
                (
                    "duration",
                    models.BooleanField(
                        choices=[
                            (
                                "1",
                                "Misses more than 15 minutes or takes excessive breaks",
                            ),
                            ("2", "Misses up to 15 minutes or takes occasional breaks"),
                            ("3", "Present and participates for entire session"),
                        ],
                        verbose_name="Present for full duration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Engagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answers",
                    models.IntegerField(
                        choices=[
                            ("1", "Unable to answer/Refuses to attempt"),
                            ("2", "Attempts to answer when prompted"),
                            ("3", "Attempts to answer independently"),
                            (
                                "4",
                                "Has to be banned from answering to give others chances",
                            ),
                        ],
                        verbose_name="Answers questions",
                    ),
                ),
                (
                    "focus",
                    models.IntegerField(
                        choices=[
                            (
                                "1",
                                "Regularly distracted, on personal devices, in loud environment, camera off, etc. AND unresponsive",
                            ),
                            (
                                "2",
                                "Regularly distracted, on personal devices, in loud environment, camera off, etc. BUT responsive",
                            ),
                            (
                                "3",
                                "Not distracted, in quiet environment, camera on, responsive, etc.",
                            ),
                        ],
                        verbose_name="Participated in discussion",
                    ),
                ),
                (
                    "roleplay",
                    models.IntegerField(
                        choices=[
                            (
                                "1",
                                "Does not engage in roleplay, prompted or independently",
                            ),
                            ("2", "Engages in roleplay when prompted"),
                            ("3", "Engages in roleplay independently"),
                        ],
                        verbose_name="Engaged in roleplay",
                    ),
                ),
                (
                    "peers",
                    models.IntegerField(choices=[], verbose_name="Peer interactions"),
                ),
                (
                    "staff",
                    models.IntegerField(choices=[], verbose_name="Staff interactions"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accepts",
                    models.IntegerField(
                        choices=[
                            (
                                "1",
                                "Does not accept feedback or responds combatively/defensively",
                            ),
                            ("2", "Reluctant to accept feedback but does"),
                            ("3", "Willingly accepts feedback from staff"),
                        ],
                        verbose_name="Accepts feedback",
                    ),
                ),
                (
                    "implements",
                    models.IntegerField(
                        choices=[
                            ("1", "Does not implement feedback"),
                            ("2", "Delays implementation of feedback"),
                            ("3", "Immediately implements feedback from staff"),
                        ],
                        verbose_name="Implements feedback",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rubric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trainee_scoring.attendance",
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trainee_scoring.engagement",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trainee_scoring.feedback",
                    ),
                ),
            ],
        ),
    ]
