# Generated by Django 6.0.6 on 2026-09-08 21:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_alter_page_table_comment_alter_profile_table_comment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "on_time",
                    models.IntegerField(
                        choices=[
                            (1, "No show"),
                            (2, "Arrives >15m late"),
                            (3, "Arrives on time"),
                        ],
                        default=1,
                        validators=[django.core.validators.MaxValueValidator(3)],
                        verbose_name="Did the trainee arrive on time (excused tardiness or absence excluded)?",
                    ),
                ),
                (
                    "dress",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Dressed inappropriately"),
                            (2, "Dressed appropriately"),
                        ],
                        default=1,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(2)],
                        verbose_name="Was the trainee appropriately dressed?",
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        choices=[
                            (
                                1,
                                "Misses more than 15 minutes or takes excessive breaks",
                            ),
                            (2, "Misses up to 15 minutes or takes occasional breaks"),
                            (3, "Present and participates for entire session"),
                        ],
                        default=1,
                        validators=[django.core.validators.MaxValueValidator(3)],
                        verbose_name="Was the trainee present for the full duration of the training?",
                    ),
                ),
                (
                    "answers",
                    models.IntegerField(
                        choices=[
                            (1, "Unable to answer/Refuses to attempt"),
                            (2, "Attempts to answer when prompted"),
                            (3, "Attempts to answer independently"),
                            (
                                4,
                                "Has to be banned from answering to give others chances",
                            ),
                        ],
                        default=1,
                        validators=[django.core.validators.MaxValueValidator(4)],
                        verbose_name="Did the trainee respond to questions/SDs?",
                    ),
                ),
                (
                    "focus",
                    models.IntegerField(
                        choices=[
                            (
                                1,
                                "Regularly distracted, on personal devices, in loud environment, camera off, etc. AND unresponsive",
                            ),
                            (
                                2,
                                "Regularly distracted, on personal devices, in loud environment, camera off, etc. BUT responsive",
                            ),
                            (
                                3,
                                "Not distracted, in quiet environment, camera on, responsive, etc.",
                            ),
                        ],
                        default=1,
                        validators=[django.core.validators.MaxValueValidator(3)],
                        verbose_name="Was the trainee focused on and engaged with the training?",
                    ),
                ),
                (
                    "roleplay",
                    models.IntegerField(
                        choices=[
                            (
                                1,
                                "Does not engage in roleplay, prompted or independently",
                            ),
                            (2, "Engages in roleplay when prompted"),
                            (3, "Engages in roleplay independently"),
                        ],
                        default=1,
                        validators=[django.core.validators.MaxValueValidator(3)],
                        verbose_name="Did the trainee engage in roleplay?",
                    ),
                ),
                (
                    "accepts",
                    models.IntegerField(
                        choices=[
                            (
                                1,
                                "Does not accept feedback or responds combatively/defensively",
                            ),
                            (2, "Reluctant to accept feedback but does"),
                            (3, "Willingly accepts feedback from staff"),
                        ],
                        default=1,
                        validators=[django.core.validators.MaxValueValidator(3)],
                        verbose_name="Did the trainee accept feedback from staff?",
                    ),
                ),
                (
                    "implements",
                    models.IntegerField(
                        choices=[
                            (1, "Does not implement feedback"),
                            (2, "Delays implementation of feedback"),
                            (3, "Immediately implements feedback from staff"),
                        ],
                        default=1,
                        validators=[django.core.validators.MaxValueValidator(3)],
                        verbose_name="Did the trainee implement feedback from staff?",
                    ),
                ),
                (
                    "trainee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.profile"
                    ),
                ),
            ],
        ),
    ]
