# Generated by Django 6.0.6 on 2026-09-08 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainee_scoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportcard",
            name="dress",
            field=models.IntegerField(
                choices=[(1, "Dressed inappropriately"), (2, "Dressed appropriately")],
                default=1,
                validators=[django.core.validators.MaxValueValidator(2)],
                verbose_name="Was the trainee appropriately dressed?",
            ),
        ),
    ]
