# Generated by Django 6.0.6 on 2026-09-08 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainee_scoring", "0002_alter_reportcard_dress"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trainee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name="reportcard",
            name="date",
        ),
        migrations.AlterField(
            model_name="reportcard",
            name="trainee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="trainee_scoring.trainee",
            ),
        ),
    ]
