# Generated by Django 6.0.6 on 2026-10-01 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainee_scoring", "0003_trainee_remove_reportcard_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportcard",
            name="day",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2)],
                default=1,
                validators=[django.core.validators.MaxValueValidator(2)],
                verbose_name="Day One or Two",
            ),
        ),
        migrations.AlterField(
            model_name="reportcard",
            name="accepts",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3)],
                default=1,
                validators=[django.core.validators.MaxValueValidator(3)],
                verbose_name="Did the trainee accept feedback from staff?",
            ),
        ),
        migrations.AlterField(
            model_name="reportcard",
            name="answers",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4)],
                default=1,
                validators=[django.core.validators.MaxValueValidator(4)],
                verbose_name="Did the trainee respond to questions/SDs?",
            ),
        ),
        migrations.AlterField(
            model_name="reportcard",
            name="dress",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2)],
                default=1,
                validators=[django.core.validators.MaxValueValidator(2)],
                verbose_name="Was the trainee appropriately dressed?",
            ),
        ),
        migrations.AlterField(
            model_name="reportcard",
            name="duration",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3)],
                default=1,
                validators=[django.core.validators.MaxValueValidator(3)],
                verbose_name="Was the trainee present for the full duration of the training?",
            ),
        ),
        migrations.AlterField(
            model_name="reportcard",
            name="focus",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3)],
                default=1,
                validators=[django.core.validators.MaxValueValidator(3)],
                verbose_name="Was the trainee focused on and engaged with the training?",
            ),
        ),
        migrations.AlterField(
            model_name="reportcard",
            name="implements",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3)],
                default=1,
                validators=[django.core.validators.MaxValueValidator(3)],
                verbose_name="Did the trainee implement feedback from staff?",
            ),
        ),
        migrations.AlterField(
            model_name="reportcard",
            name="on_time",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3)],
                default=1,
                validators=[django.core.validators.MaxValueValidator(3)],
                verbose_name="Did the trainee arrive on time (excused tardiness or absence excluded)?",
            ),
        ),
        migrations.AlterField(
            model_name="reportcard",
            name="roleplay",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3)],
                default=1,
                validators=[django.core.validators.MaxValueValidator(3)],
                verbose_name="Did the trainee engage in roleplay?",
            ),
        ),
    ]
