# Generated by Django 6.0.6 on 2026-10-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainee_scoring", "0004_reportcard_day_alter_reportcard_accepts_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainee",
            old_name="date",
            new_name="day_one",
        ),
        migrations.AddField(
            model_name="trainee",
            name="day_two",
            field=models.DateField(default="2026-12-12"),
            preserve_default=False,
        ),
    ]
