# Generated by Django 6.0.6 on 2026-10-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainee_scoring", "0005_rename_date_trainee_day_one_trainee_day_two"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportcard",
            name="day",
            field=models.DateField(),
        ),
    ]
