# Generated by Django 6.0.6 on 2026-10-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainee_scoring", "0006_alter_reportcard_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportcard",
            name="accepts",
        ),
        migrations.RemoveField(
            model_name="reportcard",
            name="implements",
        ),
        migrations.RemoveField(
            model_name="reportcard",
            name="roleplay",
        ),
    ]
