# Generated by Django 6.0.6 on 2026-10-06 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainee_scoring", "0007_remove_reportcard_accepts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportcard",
            name="trainee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="trainee_scoring.trainee",
            ),
        ),
    ]
