# Generated by Django 6.0.6 on 2026-07-02 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Behavior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("opdef", models.TextField(verbose_name="Operational Definition")),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.TextField()),
                ("explanation", models.TextField()),
                (
                    "meetsdef",
                    models.BooleanField(
                        default=False, verbose_name="Meets Operational Definition?"
                    ),
                ),
                (
                    "example",
                    models.BooleanField(
                        default=False, verbose_name="Is an Example Event?"
                    ),
                ),
                (
                    "behavior",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_collection.behavior",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="behavior",
            name="examples",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examples",
                to="data_collection.event",
                verbose_name="Example Events",
            ),
        ),
        migrations.CreateModel(
            name="EventSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_id", models.IntegerField()),
                (
                    "ordered",
                    models.BooleanField(default=False, verbose_name="Is Ordered?"),
                ),
                ("index", models.IntegerField()),
                (
                    "events",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_collection.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FRQ", "Frequency"),
                            ("DUR", "Duration"),
                            ("RTE", "Rate"),
                            ("LTC", "Latency"),
                            ("IRT", "Inter-response Time"),
                            ("PIV", "Partial Interval"),
                            ("WIV", "Whole Interval"),
                            ("MOM", "Momentary Time Sampling"),
                        ],
                        max_length=3,
                        verbose_name="Data Collection Method",
                    ),
                ),
                (
                    "behavior",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_behavior",
                        to="data_collection.eventset",
                    ),
                ),
                (
                    "events",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_events",
                        to="data_collection.eventset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Results",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("results", models.JSONField()),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_collection.program",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
