# Generated by Django 6.0.6 on 2026-06-14 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('opdef', models.TextField(verbose_name='Operational Definition')),
                ('data_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField()),
                ('meetsdef', models.BooleanField(verbose_name='Meets Operational Definition?')),
                ('example', models.BooleanField(default=False, verbose_name='Is an Example Event?')),
                ('behavior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collection.behavior')),
            ],
        ),
        migrations.AddField(
            model_name='behavior',
            name='examples',
            field=models.ManyToManyField(blank=True, related_name='example_events', to='data_collection.event', verbose_name='Examples'),
        ),
    ]
