# Generated by Django 6.0.6 on 2026-07-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_collection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="behavior",
            name="offset",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="behavior",
            name="onset",
            field=models.TextField(blank=True, null=True),
        ),
    ]
